import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Eglė",
      email: "egllegriciute@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Tom",
      email: "tom@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Barlean's, Borage Oil Supplement, 60 Softgels",
      category: "Supplements",
      image: "/images/01.png",
      price: 21.43,
      countInStock: 2,
      brand: "Barlean's",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Barlean's, Essential Woman Supplement, 120 Softgels",
      category: "Supplements",
      image: "/images/02.png",
      price: 25.95,
      countInStock: 0,
      brand: "Barlean's",
      rating: 3.5,
      numReviews: 3,
      description: "high quality product",
    },
    {
      name: "Barlean's, Fresh Catch, Fish Oil Supplement, Omega-3 EPA/DHA, Orange, 250 Softgels",
      category: "Supplements",
      image: "/images/03.png",
      price: 22.48,
      countInStock: 0,
      brand: "Barlean's",
      rating: 5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Barlean's, Olive Leaf Complex, 120 Softgels",
      category: "Supplements",
      image: "/images/04.png",
      price: 37.24,
      countInStock: 97,
      brand: "Barlean's",
      rating: 1,
      numReviews: 2,
      description: "high quality product",
    },
    {
      name: "Barlean's, Evening Primrose Oil, 120 Softgels",
      category: "Supplements",
      image: "/images/05.png",
      price: 28.56,
      countInStock: 432,
      brand: "Barlean's",
      rating: 5,
      numReviews: 30,
      description: "high quality product",
    },
    {
      name: "Barlean's, Lignan Flax Oil, 250 Softgels",
      category: "Supplements",
      image: "/images/06.png",
      price: 25.81,
      countInStock: 988,
      brand: "Barlean's",
      rating: 4.5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      name: "Barlean's, Organic Virgin Coconut Oil, Island Fresh, 16 fl oz (473 ml)",
      category: "Supplements",
      image: "/images/07.png",
      price: 13.63,
      countInStock: 511,
      brand: "Barlean's",
      rating: 5,
      numReviews: 114,
      description: "high quality product",
    },
    {
      name: "Barlean's, Essential Woman, Nurture, 12 fl oz (355 ml)",
      category: "Supplements",
      image: "/images/08.png",
      price: 25.72,
      countInStock: 1002,
      brand: "Barlean's",
      rating: 5,
      numReviews: 837,
      description: "high quality product",
    },
    {
      name: "Barlean's, Plant Based Total Omega 3 · 6 · 9, Pomegranate Blueberry Smoothie, 3,980 mg, 16 oz (454 g)",
      category: "Supplements",
      image: "/images/09.png",
      price: 27.33,
      countInStock: 76,
      brand: "Barlean's",
      rating: 4,
      numReviews: 82,
      description: "high quality product",
    },
    {
      name: "Barlean's, Organic Greens, 8.47 oz (240 g)",
      category: "Supplements",
      image: "/images/10.png",
      price: 39.31,
      countInStock: 2189,
      brand: "Barlean's",
      rating: 5,
      numReviews: 3090,
      description: "high quality product",
    },
    {
      name: "Barlean's, Seriously Delicious, Omega-3 Fish Oil, Mango Peach Smoothie, 1,080 mg, 16 oz (454 g)",
      category: "Supplements",
      image: "/images/11.png",
      price: 19.29,
      countInStock: 300,
      brand: "Barlean's",
      rating: 4.5,
      numReviews: 450,
      description: "high quality product",
    },
    {
      name: "Barlean's, Seriously Delicious, Liquid Vitamin D3, Strawberry Milkshake, 125 mcg (5,000 IU), 5.6 oz (159 g)",
      category: "Supplements",
      image: "/images/12.png",
      price: 6.82,
      countInStock: 653,
      brand: "Barlean's",
      rating: 3.5,
      numReviews: 12,
      description: "high quality product",
    },
  ],
};

export default data;
