const data = {
    products: [
        {
            _id: '1',
            name: 'Barlean\'s, Borage Oil Supplement, 60 Softgels',
            category: 'Supplements',
            image: '/images/01.png',
            price: 21.43,
            brand: 'Barlean\'s',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Barlean\'s, Essential Woman Supplement, 120 Softgels',
            category: 'Supplements',
            image: '/images/02.png',
            price: 25.95,
            brand: 'Barlean\'s',
            rating: 3.5,
            numReviews: 3,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Barlean\'s, Fresh Catch, Fish Oil Supplement, Omega-3 EPA/DHA, Orange, 250 Softgels',
            category: 'Supplements',
            image: '/images/03.png',
            price: 22.48,
            brand: 'Barlean\'s',
            rating: 5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Barlean\'s, Olive Leaf Complex, 120 Softgels',
            category: 'Supplements',
            image: '/images/04.png',
            price: 37.24,
            brand: 'Barlean\'s',
            rating: 1,
            numReviews: 2,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Barlean\'s, Evening Primrose Oil, 120 Softgels',
            category: 'Supplements',
            image: '/images/05.png',
            price: 28.56,
            brand: 'Barlean\'s',
            rating: 5,
            numReviews: 30,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Barlean\'s, Lignan Flax Oil, 250 Softgels',
            category: 'Supplements',
            image: '/images/06.png',
            price: 25.81,
            brand: 'Barlean\'s',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
    ],
};

export default data;